version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root@123.
      MYSQL_DATABASE: moonglade
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123.
